package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlogInfo<M extends BaseBlogInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setBlogTitle(java.lang.String blogTitle) {
		set("blog_title", blogTitle);
	}

	public java.lang.String getBlogTitle() {
		return get("blog_title");
	}

	public void setBlogName(java.lang.String blogName) {
		set("blog_name", blogName);
	}

	public java.lang.String getBlogName() {
		return get("blog_name");
	}

	public void setBlogDescription(java.lang.String blogDescription) {
		set("blog_description", blogDescription);
	}

	public java.lang.String getBlogDescription() {
		return get("blog_description");
	}

	public void setEnabled(java.lang.Integer enabled) {
		set("enabled", enabled);
	}

	public java.lang.Integer getEnabled() {
		return get("enabled");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
