package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSecretMessage<M extends BaseSecretMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSendId(java.lang.Integer sendId) {
		set("send_id", sendId);
	}

	public java.lang.Integer getSendId() {
		return get("send_id");
	}

	public void setReceiveId(java.lang.Integer receiveId) {
		set("receive_id", receiveId);
	}

	public java.lang.Integer getReceiveId() {
		return get("receive_id");
	}

	public void setMessageTopic(java.lang.String messageTopic) {
		set("message_topic", messageTopic);
	}

	public java.lang.String getMessageTopic() {
		return get("message_topic");
	}

	public void setMessageContent(java.lang.String messageContent) {
		set("message_content", messageContent);
	}

	public java.lang.String getMessageContent() {
		return get("message_content");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
	}

	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
