package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticleSort<M extends BaseArticleSort<M>> extends Model<M> implements IBean {

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}

	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}

	public java.lang.String getTypeName() {
		return getStr("type_name");
	}

	public void setTypeCode(java.lang.String typeCode) {
		set("type_code", typeCode);
	}

	public java.lang.String getTypeCode() {
		return getStr("type_code");
	}

	public void setDr(java.lang.Long dr) {
		set("dr", dr);
	}

	public java.lang.Long getDr() {
		return getLong("dr");
	}

}
