package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRank<M extends BaseUserRank<M>> extends Model<M> implements IBean {

	public void setRankId(java.lang.Integer rankId) {
		set("rank_id", rankId);
	}

	public java.lang.Integer getRankId() {
		return get("rank_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setUserRankId(java.lang.Integer userRankId) {
		set("user_rank_id", userRankId);
	}

	public java.lang.Integer getUserRankId() {
		return get("user_rank_id");
	}

	public void setRankMark(java.lang.Integer rankMark) {
		set("rank_mark", rankMark);
	}

	public java.lang.Integer getRankMark() {
		return get("rank_mark");
	}

	public void setRankName(java.lang.String rankName) {
		set("rank_name", rankName);
	}

	public java.lang.String getRankName() {
		return get("rank_name");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
