package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}

	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}

	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setErrMsg(java.lang.String errMsg) {
		set("err_msg", errMsg);
	}

	public java.lang.String getErrMsg() {
		return getStr("err_msg");
	}

	public void setErrCode(java.lang.Integer errCode) {
		set("err_code", errCode);
	}

	public java.lang.Integer getErrCode() {
		return getInt("err_code");
	}

	public void setClassName(java.lang.String className) {
		set("class_name", className);
	}

	public java.lang.String getClassName() {
		return getStr("class_name");
	}

	public void setMethodName(java.lang.String methodName) {
		set("method_name", methodName);
	}

	public java.lang.String getMethodName() {
		return getStr("method_name");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setSpendTime(java.lang.Long spendTime) {
		set("spend_time", spendTime);
	}

	public java.lang.Long getSpendTime() {
		return getLong("spend_time");
	}

	public void setParams(java.lang.String params) {
		set("params", params);
	}

	public java.lang.String getParams() {
		return getStr("params");
	}

}
