package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStayMessage<M extends BaseStayMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setStayUserId(java.lang.Integer stayUserId) {
		set("stay_user_id", stayUserId);
	}

	public java.lang.Integer getStayUserId() {
		return get("stay_user_id");
	}

	public void setMessageContent(java.lang.String messageContent) {
		set("message_content", messageContent);
	}

	public java.lang.String getMessageContent() {
		return get("message_content");
	}

	public void setStayUserDt(java.util.Date stayUserDt) {
		set("stay_user_dt", stayUserDt);
	}

	public java.util.Date getStayUserDt() {
		return get("stay_user_dt");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
