package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFriendlyLink<M extends BaseFriendlyLink<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLinkId(java.lang.String linkId) {
		set("link_id", linkId);
	}

	public java.lang.String getLinkId() {
		return get("link_id");
	}

	public void setLinkName(java.lang.String linkName) {
		set("link_name", linkName);
	}

	public java.lang.String getLinkName() {
		return get("link_name");
	}

	public void setLinkUrl(java.lang.String linkUrl) {
		set("link_url", linkUrl);
	}

	public java.lang.String getLinkUrl() {
		return get("link_url");
	}

	public void setLinkLogo(java.lang.String linkLogo) {
		set("link_logo", linkLogo);
	}

	public java.lang.String getLinkLogo() {
		return get("link_logo");
	}

	public void setShowOrder(java.lang.Integer showOrder) {
		set("show_order", showOrder);
	}

	public java.lang.Integer getShowOrder() {
		return get("show_order");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
