package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVisitor<M extends BaseVisitor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setVisitorId(java.lang.Integer visitorId) {
		set("visitor_id", visitorId);
	}

	public java.lang.Integer getVisitorId() {
		return get("visitor_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setVisitorTime(java.util.Date visitorTime) {
		set("visitor_time", visitorTime);
	}

	public java.util.Date getVisitorTime() {
		return get("visitor_time");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
