package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlogFriend<M extends BaseBlogFriend<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setFriendId(java.lang.Integer friendId) {
		set("friend_id", friendId);
	}

	public java.lang.Integer getFriendId() {
		return get("friend_id");
	}

	public void setAddDt(java.util.Date addDt) {
		set("add_dt", addDt);
	}

	public java.util.Date getAddDt() {
		return get("add_dt");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
