package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePowerList<M extends BasePowerList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBl_userId(java.lang.Integer bl_userId) {
		set("bl__user_id", bl_userId);
	}

	public java.lang.Integer getBl_userId() {
		return getInt("bl__user_id");
	}

	public void setPowerId(java.lang.String powerId) {
		set("power_id", powerId);
	}

	public java.lang.String getPowerId() {
		return getStr("power_id");
	}

	public void setPowerName(java.lang.String powerName) {
		set("power_name", powerName);
	}

	public java.lang.String getPowerName() {
		return getStr("power_name");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return getInt("dr");
	}

}
