package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContentInfo<M extends BaseContentInfo<M>> extends Model<M> implements IBean {

	public void setContentId(java.lang.Integer contentId) {
		set("content_id", contentId);
	}

	public java.lang.Integer getContentId() {
		return get("content_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setTypeId(java.lang.String typeId) {
		set("type_id", typeId);
	}

	public java.lang.String getTypeId() {
		return get("type_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreateDt(java.util.Date createDt) {
		set("create_dt", createDt);
	}

	public java.util.Date getCreateDt() {
		return get("create_dt");
	}

	public void setReadCount(java.lang.Integer readCount) {
		set("read_count", readCount);
	}

	public java.lang.Integer getReadCount() {
		return get("read_count");
	}

	public void setLaudCount(java.lang.Integer laudCount) {
		set("laud_count", laudCount);
	}

	public java.lang.Integer getLaudCount() {
		return get("laud_count");
	}

	public void setCommentCount(java.lang.Integer commentCount) {
		set("comment_count", commentCount);
	}

	public java.lang.Integer getCommentCount() {
		return get("comment_count");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
