package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlogUser<M extends BaseBlogUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("user_pwd", userPwd);
	}

	public java.lang.String getUserPwd() {
		return get("user_pwd");
	}

	public void setUserPhone(java.lang.Integer userPhone) {
		set("user_phone", userPhone);
	}

	public java.lang.Integer getUserPhone() {
		return get("user_phone");
	}

	public void setUserSex(java.lang.String userSex) {
		set("user_sex", userSex);
	}

	public java.lang.String getUserSex() {
		return get("user_sex");
	}

	public void setUserQq(java.lang.Integer userQq) {
		set("user_qq", userQq);
	}

	public java.lang.Integer getUserQq() {
		return get("user_qq");
	}

	public void setUserEmail(java.lang.String userEmail) {
		set("user_email", userEmail);
	}

	public java.lang.String getUserEmail() {
		return get("user_email");
	}

	public void setUserAddress(java.lang.String userAddress) {
		set("user_address", userAddress);
	}

	public java.lang.String getUserAddress() {
		return get("user_address");
	}

	public void setUserMark(java.lang.Integer userMark) {
		set("user_mark", userMark);
	}

	public java.lang.Integer getUserMark() {
		return get("user_mark");
	}

	public void setUserRankId(java.lang.String userRankId) {
		set("user_rank_id", userRankId);
	}

	public java.lang.String getUserRankId() {
		return get("user_rank_id");
	}

	public void setUserLastLoginDt(java.lang.String userLastLoginDt) {
		set("user_last_login_dt", userLastLoginDt);
	}

	public java.lang.String getUserLastLoginDt() {
		return get("user_last_login_dt");
	}

	public void setUserBirthday(java.util.Date userBirthday) {
		set("user_birthday", userBirthday);
	}

	public java.util.Date getUserBirthday() {
		return get("user_birthday");
	}

	public void setUserDescription(java.lang.String userDescription) {
		set("user_description", userDescription);
	}

	public java.lang.String getUserDescription() {
		return get("user_description");
	}

	public void setUserImageUrl(java.lang.String userImageUrl) {
		set("user_image_url", userImageUrl);
	}

	public java.lang.String getUserImageUrl() {
		return get("user_image_url");
	}

	public void setUserSchool(java.lang.String userSchool) {
		set("user_school", userSchool);
	}

	public java.lang.String getUserSchool() {
		return get("user_school");
	}

	public void setUserRegisterTime(java.util.Date userRegisterTime) {
		set("user_register_time", userRegisterTime);
	}

	public java.util.Date getUserRegisterTime() {
		return get("user_register_time");
	}

	public void setUserWeibo(java.lang.String userWeibo) {
		set("user_weibo", userWeibo);
	}

	public java.lang.String getUserWeibo() {
		return get("user_weibo");
	}

	public void setUserBloodType(java.lang.String userBloodType) {
		set("user_blood_type", userBloodType);
	}

	public java.lang.String getUserBloodType() {
		return get("user_blood_type");
	}

	public void setUserSays(java.lang.String userSays) {
		set("user_says", userSays);
	}

	public java.lang.String getUserSays() {
		return get("user_says");
	}

	public void setUserEnabled(java.lang.Integer userEnabled) {
		set("user_enabled", userEnabled);
	}

	public java.lang.Integer getUserEnabled() {
		return get("user_enabled");
	}

	public void setUserPower(java.lang.String userPower) {
		set("user_power", userPower);
	}

	public java.lang.String getUserPower() {
		return get("user_power");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
