package com.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAttention<M extends BaseUserAttention<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setAttentionId(java.lang.Integer attentionId) {
		set("attention_id", attentionId);
	}

	public java.lang.Integer getAttentionId() {
		return get("attention_id");
	}

	public void setAttentionDt(java.util.Date attentionDt) {
		set("attention_dt", attentionDt);
	}

	public java.util.Date getAttentionDt() {
		return get("attention_dt");
	}

	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}

	public java.lang.Integer getDr() {
		return get("dr");
	}

}
