package com.blog.common.model;

import com.blog.common.model.base.BaseArticleSort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleSort extends BaseArticleSort<ArticleSort> {
	public static final ArticleSort dao = new ArticleSort().dao();
}
