package com.blog.common.model;

import com.blog.common.model.base.BaseBlogInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlogInfo extends BaseBlogInfo<BlogInfo> {
	public static final BlogInfo dao = new BlogInfo().dao();
}
