package com.blog.common.model;

import com.blog.common.model.base.BaseBlogFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlogFriend extends BaseBlogFriend<BlogFriend> {
	public static final BlogFriend dao = new BlogFriend().dao();
}
