package com.blog.common.model;

import com.blog.common.model.base.BaseBlogUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlogUser extends BaseBlogUser<BlogUser> {
	public static final BlogUser dao = new BlogUser().dao();
}
