package com.blog.common.model;

import com.blog.common.model.base.BaseContentInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContentInfo extends BaseContentInfo<ContentInfo> {
	public static final ContentInfo dao = new ContentInfo().dao();
}
