package com.blog.common.model;

import com.blog.common.model.base.BaseFriendlyLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendlyLink extends BaseFriendlyLink<FriendlyLink> {
	public static final FriendlyLink dao = new FriendlyLink().dao();
}
