package com.blog.common.model;

import com.blog.common.model.base.BasePowerList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PowerList extends BasePowerList<PowerList> {
	public static final PowerList dao = new PowerList().dao();
}
