package com.blog.common.model;

import com.blog.common.model.base.BaseSecretMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecretMessage extends BaseSecretMessage<SecretMessage> {
	public static final SecretMessage dao = new SecretMessage().dao();
}
