package com.blog.common.model;

import com.blog.common.model.base.BaseStayMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StayMessage extends BaseStayMessage<StayMessage> {
	public static final StayMessage dao = new StayMessage().dao();
}
