package com.blog.common.model;

import com.blog.common.model.base.BaseSysLoginRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLoginRecord extends BaseSysLoginRecord<SysLoginRecord> {
	public static final SysLoginRecord dao = new SysLoginRecord().dao();
}
