package com.blog.common.model;

import com.blog.common.model.base.BaseSysRoleRes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleRes extends BaseSysRoleRes<SysRoleRes> {
	public static final SysRoleRes dao = new SysRoleRes().dao();
}
