package com.blog.common.model;

import com.blog.common.model.base.BaseSystemMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemMessage extends BaseSystemMessage<SystemMessage> {
	public static final SystemMessage dao = new SystemMessage().dao();
}
