package com.blog.common.model;

import com.blog.common.model.base.BaseUserRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRank extends BaseUserRank<UserRank> {
	public static final UserRank dao = new UserRank().dao();
}
