package com.blog.common.model;

import com.blog.common.model.base.BaseUserAttention;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAttention extends BaseUserAttention<UserAttention> {
	public static final UserAttention dao = new UserAttention().dao();
}
